Mods to activate metonly mode; use same queue script on mpiexec systems as queueing systems; added loop over layers and linking to full or metonly layer to queue script; tested

diff --git a/qscript.template b/qscript.template
--- a/qscript.template
+++ b/qscript.template
@@ -34,7 +34,7 @@ THIS=%jobtype%.%queuesyslc%  # name of this script for use in log messages
 SCRIPTDIR=%scriptdir%
 SYSLOG=%syslog%
 CYCLEDIR=%advisdir%
-CYCLE=`basename %advisdir%`
+CYCLE=$(basename %advisdir%)
 CYCLELOG=$CYCLEDIR/cycle.log
 SCENARIO=%scenario%
 SCENARIODIR=$CYCLEDIR/$SCENARIO
@@ -45,13 +45,11 @@ cd $SCENARIODIR 2> >(awk -v this=$THIS -v level=ERROR -f $SCRIPTDIR/monitoring/t
 #----------------------------------------------------------------------------
 #        L O G   M E S S A G E S   T O   S T A R T   T H E   J O B
 #----------------------------------------------------------------------------
-DATETIME=`date +'%Y-%h-%d-T%H:%M:%S%z'`
 echo "Starting $THIS in $SCENARIODIR with %queuesys% Job ID ${%JOBID%}; %queuesys% submit directory ${%JOBDIR%}; and %queuesys% submit host ${%JOBHOST%}."  2>&1 | awk -v this=$THIS -v level=INFO -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG | tee --append $CYCLELOG | tee --append $SYSLOG
-echo "\"start\" : \"$DATETIME\", \"jobid\" : \"${%JOBID%}\"" > %jobtype%.%scenario%.run.start # <-OVERWRITE
-echo "\"jobtype\" : \"%jobtype%\", \"submit\" : null, \"jobid\" : \"${%JOBID%}\", \"start\" : \"$DATETIME\", \"finish\" : null, \"error\" : null" >> jobs.status
+
 # record which cluster nodes we have to scenario.log
-echo "INFO: $THIS: %JOBNODES%: $%JOBNODES%"
-echo "INFO: $THIS: hostname: "`hostname`
+echo "INFO: $THIS: %JOBNODES%: $%JOBNODES%"   #QUEUEONLY
+echo "INFO: $THIS: hostname: "$(hostname)
 echo "INFO: $THIS: PATH : $PATH"
 echo "INFO: $THIS: LD_LIBRARY_PATH : $LD_LIBRARY_PATH"
 #
@@ -63,93 +61,127 @@ if [[ -e "%adcircdir%/../adcirc.bin.buildinfo.json" && ! -e "adcirc.bin.buildinf
    cp "%adcircdir%/../adcirc.bin.buildinfo.json" . 2>> $SYSLOG
    echo "adcirc.file.metadata.build : adcirc.bin.buildinfo.json" >> run.properties
 fi
-echo "time.hpc.job.%jobtype%.start : $DATETIME" >> $SCENARIO.run.properties
+echo "time.hpc.job.%jobtype%.start : $(date +'%Y-%h-%d-T%H:%M:%S%z')" >> $SCENARIO.run.properties
 echo "hpc.job.%jobtype%.jobid : ${%JOBID%}" >> $SCENARIO.run.properties
-echo "hpc.job.%jobtype%.nodelist : ( %JOBNODES% )" >> $SCENARIO.run.properties
-echo "hpc.job.%jobtype%.hostname : $HOSTNAME" >> $SCENARIO.run.properties
-echo "hpc.job.%jobtype%.qnnodes : $%JOBNNODES%" >> $SCENARIO.run.properties
-echo "hpc.job.%jobtype%.qntasks-per-node : $%JOBNTASKSPERNODE%" >> $SCENARIO.run.properties
-echo "hpc.job.%jobtype%.qntasks : $%JOBNTASKS%" >> $SCENARIO.run.properties
-echo "hpc.job.%jobtype%.joblog : %advisdir%/%scenario%/%jobtype%.out" >> $SCENARIO.run.properties
+echo "hpc.job.%jobtype%.nodelist : ( %JOBNODES% )" >> $SCENARIO.run.properties                #QUEUEONLY
+echo "hpc.job.%jobtype%.hostname : $HOSTNAME" >> $SCENARIO.run.properties                     #QUEUEONLY
+echo "hpc.job.%jobtype%.qnnodes : $%JOBNNODES%" >> $SCENARIO.run.properties                   #QUEUEONLY
+echo "hpc.job.%jobtype%.qntasks-per-node : $%JOBNTASKSPERNODE%" >> $SCENARIO.run.properties   #QUEUEONLY
+echo "hpc.job.%jobtype%.qntasks : $%JOBNTASKS%" >> $SCENARIO.run.properties                   #QUEUEONLY
+echo "hpc.job.%jobtype%.joblog : %advisdir%/%scenario%/%jobtype%.out" >> $SCENARIO.run.properties #QUEUEONLY
 #
 #----------------------------------------------------------------------------
-#                  W I N D 1 0 M   L A Y E R
+#              L A Y E R   S P E C I F I C A T I O N
 #----------------------------------------------------------------------------
 #
 jobtype="%jobtype%"
 createWind10mLayer="%wind10mlayer%"
-if [[ $createWind10mLayer == "yes" && ${jobtype:0:4} != "prep" ]]; then
-   # duplicate the original meteorological output files for use with Wind10m layer
-   for file in $(ls fort.7*); do
-      cp $file orig.$file
-   done
-   CMD="%cmd%"
-   echo "cycle $CYCLE: $SCENARIO: $THIS: %jobtype%.Wind10m.%scenario% job ${%JOBID%} starting in $SCENARIODIR with the following command: $CMD" 2>&1 | awk -v level=INFO -v this=$THIS -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG | tee --append $CYCLELOG | tee --append $SYSLOG
-   $CMD
-   ERROVALUE=$?  # capture exit status
-   if [[ $ERROVALUE -ne 0 ]]; then
-      ERROMSG="$ERROMSG The %jobtype%.Wind10m.%scenario% job ended with an exit status that indicates an error occurred."
-      echo $ERROMSG
-   fi
-   # rename meteorological output files to indicate Wind10m layer
-   for file in $(ls fort.7*); do
-      mv $file Wind10m.$file
-   done
-   # restore empty meteorological output files copied earlier for use in recording full layer data
-   for file in $(ls orig.fort.7*); do
-      mv $file ${file#orig.}
-   done
-   # unpack subdomain fort.15 files for use in generating full layer
-   tar xvf $SCENARIO.fort.15.tar
+declare -a layers=( $SCENARIO )
+if [[ $createWind10mLayer == "yes" && $jobtype != "partmesh" && $jobtype != "prep20" && $jobtype != "prep13" ]]; then
+   layers=( ${SCENARIO}Wind10m ${layers[@]} )
 fi
 #
 #----------------------------------------------------------------------------
-#                  E X E C U T E   T H E   J O B
+#                 L O O P   O V E R   L A Y E R S
 #----------------------------------------------------------------------------
-# log the command to run
-CMD="%cmd%"
-echo "cycle $CYCLE: $SCENARIO: $THIS: %jobtype%.%scenario% job ${%JOBID%} starting in $SCENARIODIR with the following command: $CMD" 2>&1 | awk -v level=INFO -v this=$THIS -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG | tee --append $CYCLELOG | tee --append $SYSLOG
-$CMD
-ERROVALUE=$?  # capture exit status
 #
-#----------------------------------------------------------------------------
-#           C H E C K   S T A T U S   O F   R E S U L T S
-#----------------------------------------------------------------------------
-DATETIME=`date +'%Y-%h-%d-T%H:%M:%S%z'`
-ERROMSG=""
-RUNSUFFIX="finish"
-if [ $ERROVALUE -eq 0 ] ; then
-   if [[ $JOBTYPE = adcirc || $JOBTYPE = adcswan || $JOBTYPE = padcirc || $JOBTYPE = padcswan ]]; then
-      # look for numerical instability errors in the stdout/stderr files
-      for file in adcirc.log $SCENARIOLOG ; do
-         if [ -e $file ]; then
-            numMsg=`grep WarnElev $file | wc -l`
-            if [ $numMsg = 0 ]; then
-               echo "$THIS: No numerical instability detected in $file after completion of %jobtype%.%scenario% job ${%JOBID%}." 2>&1 | awk -v level=INFO -v this=$THIS -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG
-            else
-               ERROVALUE=1
-               ERROMSG="$ERROMSG Detected $numMsg numerical instability messages in $file after completion of %jobtype%.%scenario% job ${%JOBID%}."
-               RUNSUFFIX="error"
-            fi
+for layer in ${layers[@]}; do
+   if [[ -e "fort.15" ]]; then
+      echo "$THIS: $layer: deleting fort.15" # jgfdebug
+      rm fort.15 2>> $SCENARIOLOG
+   fi
+   #echo "$THIS: $layer: linking ${layer}.fort.15" # jgfdebug
+   ln -s ${layer}.fort.15 fort.15 2>> $SCENARIOLOG
+   # if this is not a prep job, untar the corresponding fort.15 files
+   # and link to the proper meteorological output files
+   if [[ ${jobtype:0:4} != "prep" && $jobtype != "partmesh" ]]; then
+      # unpack subdomain fort.15 files for use in generating the layer
+      #echo "$THIS: $layer: unpacking ${layer}.fort.15.tar" # jgfdebug
+      tar xvf ${layer}.fort.15.tar 2>> $SCENARIOLOG 2>&1
+      # link to empty meteorological output files created in prep phase
+      for layerFile in $(ls ${layer}.fort.7*); do
+         if [[ -e ${layerFile#$layer.} ]]; then
+            #echo "$THIS: $layer: unpacking ${layer}.fort.15.tar" # jgfdebug
+            rm ${layerFile#$layer.} 2>> $SCENARIOLOG
          fi
+         ln -s $layerFile ${layerFile#$layer.} 2>> $SCENARIOLOG
       done
    fi
-else
-   ERROMSG="$ERROMSG The %jobtype%.%scenario% job ended with an exit status that indicates an error occurred."
-   RUNSUFFIX="error"
-fi
+   #
+   #       E X E C U T E   T H E   J O B
+   #
+   CMD="%cmd%"
+   echo "cycle $CYCLE: $SCENARIO: $THIS: $jobtype.$layer job ${%JOBID%} starting in $SCENARIODIR with the following command: $CMD" 2>&1 | awk -v level=INFO -v this=$THIS -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG | tee --append $CYCLELOG | tee --append $SYSLOG
+   echo "\"start\" : \"$(date +'%Y-%h-%d-T%H:%M:%S%z')\", \"jobid\" : \"${%JOBID%}\"" > $jobtype.${layer}.run.start # <-OVERWRITE
+   echo "\"jobtype\" : \"$jopbtype\", \"submit\" : null, \"jobid\" : \"${%JOBID%}\", \"start\" : \"$(date +'%Y-%h-%d-T%H:%M:%S%z')\", \"finish\" : null, \"error\" : null" >> jobs.status
+   $CMD
+   ERROVALUE=$?  # capture exit status
+   #
+   #       C H E C K   S T A T U S   O F   R E S U L T S
+   #
+   ERROMSG=""
+   RUNSUFFIX="finish"
+   if [ $ERROVALUE -eq 0 ] ; then
+      if [[ ${jobtype:0:4} != "prep" && $jobtype != "partmesh" ]]; then
+         # look for numerical instability errors in the stdout/stderr files
+         for file in adcirc.log $SCENARIOLOG ; do
+            if [ -e $file ]; then
+               numMsg=$(grep WarnElev $file | wc -l)
+               if [ $numMsg = 0 ]; then
+                  echo "$THIS: No numerical instability detected in '$file' after completion of $jobtype.$layer job ${%JOBID%}." 2>&1 | awk -v level=INFO -v this=$THIS -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG
+               else
+                  ERROVALUE=1
+                  ERROMSG="$ERROMSG Detected $numMsg numerical instability messages in '$file' after completion of $jobtype.$layer job ${%JOBID%}."
+                  RUNSUFFIX="error"
+               fi
+            fi
+         done
+      fi
+   else
+      ERROMSG="$ERROMSG The $jobtype.$layer job ended with an exit status that indicates an error occurred."
+      RUNSUFFIX="error"
+   fi
+   #
+   echo "cycle $CYCLE: $SCENARIO: $THIS: $jobtype.$layer job $%JOBID% finished in $SCENARIODIR with return value = $ERROVALUE" 2>&1 | awk -v level=INFO -v this=$THIS -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG | tee --append $CYCLELOG | tee --append $SYSLOG
+   #
+   #     R E P O R T   J O B   F A I L U R E   O R   S U C C E S S
+   #
+   if [ $ERROVALUE != 0 ]; then
+      echo "cycle $CYCLE: $SCENARIO: $THIS: $ERROMSG" 2>&1 | awk -v this=$THIS -v level=ERROR -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG | tee --append $CYCLELOG | tee --append $SYSLOG
+      echo "\"$RUNSUFFIX\" : \"$(date +'%Y-%h-%d-T%H:%M:%S%z')\", \"message\" : \"$ERROMSG\"" > $jobtype.${layer}.run.${RUNSUFFIX}  # <-OVERWRITE
+      echo "\"jobtype\" : \"$jobtype\", \"submit\" : null, \"jobid\" : \"${%JOBID%}\", \"start\" : null, \"finish\" : null, \"error\" : \"$(date +'%Y-%h-%d-T%H:%M:%S%z')\"" >> jobs.status
+   else
+      echo "\"jobtype\" : \"$jobtype\", \"submit\" : null, \"jobid\" : \"${%JOBID%}\", \"start\" : null, \"finish\" : \"$(date +'%Y-%h-%d-T%H:%M:%S%z')\", \"error\" : null" >> jobs.status
+      echo "\"$RUNSUFFIX\" : \"$(date +'%Y-%h-%d-T%H:%M:%S%z')\"" > $jobtype.%scenario%.run.$RUNSUFFIX
+   fi
+   echo "time.hpc.job.$jobtype.${RUNSUFFIX} : $(date +'%Y-%h-%d-T%H:%M:%S%z')" >> $SCENARIO.run.properties
+   echo "-----------------------------------------------------------------------"
+   #
+   # if this is a prepall or prep15 job, tar up the subdomain fort.15 files
+   # and copy the meteorological output files to their own filenames
+   #
+   if [[ $jobtype == "prepall" || $jobtype == "prep15" ]]; then
+      tar cvf ${layer}.fort.15.tar PE*/fort.15 2>>$SYSLOG 2>&1
+      rm PE*/fort.15 2>> $SYSLOG
+      for file in $(ls fort.7*); do
+         mv $file ${layer}.$file
+      done
+   fi
+done
 #
-echo "cycle $CYCLE: $SCENARIO: $THIS: %jobtype%.%scenario% job $%JOBID% finished in $SCENARIODIR with return value = $ERROVALUE" 2>&1 | awk -v level=INFO -v this=$THIS -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG | tee --append $CYCLELOG | tee --append $SYSLOG
-
-#
-#  write reason for job failure
-if [ $ERROVALUE != 0 ]; then
-   echo "cycle $CYCLE: $SCENARIO: $THIS: $ERROMSG" 2>&1 | awk -v this=$THIS -v level=ERROR -f $SCRIPTDIR/monitoring/timestamp.awk | tee --append $SCENARIOLOG | tee --append $CYCLELOG | tee --append $SYSLOG
-   echo "\"$RUNSUFFIX\" : \"$DATETIME\", \"message\" : \"$ERROMSG\"" > %jobtype%.%scenario%.run.${RUNSUFFIX}  # <-OVERWRITE
-   echo "\"jobtype\" : \"%jobtype%\", \"submit\" : null, \"jobid\" : \"${%JOBID%}\", \"start\" : null, \"finish\" : null, \"error\" : \"$DATETIME\"" >> jobs.status
-else
-   echo "\"jobtype\" : \"%jobtype%\", \"submit\" : null, \"jobid\" : \"${%JOBID%}\", \"start\" : null, \"finish\" : \"$DATETIME\", \"error\" : null" >> jobs.status
-   echo "\"$RUNSUFFIX\" : \"$DATETIME\"" > %jobtype%.%scenario%.run.$RUNSUFFIX
+# finalize by setting the symbolic links for the fort.15 file and
+# the meteorology output files to the full output
+# (i.e., those that include wind reduction)
+if [[ -e "fort.15" ]]; then
+   rm fort.15 2>> $SCENARIOLOG
 fi
-echo "time.hpc.job.%jobtype%.${RUNSUFFIX} : $DATETIME" >> $SCENARIO.run.properties
-echo "-----------------------------------------------------------------------"
+ln -s $SCENARIO.fort.15 fort.15 2>> $SCENARIOLOG
+#
+for file in $(ls fort.7*); do
+   if [[ -e $file ]]; then
+      rm $file 2>> $SCENARIOLOG
+   fi
+done
+for file in $(ls ${SCENARIO}.fort.7*); do
+   ln -s $file ${file#$SCENARIO.} 2>> $SCENARIOLOG
+done
